name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Refresh Dropbox Token
      run: |
        response=$(curl -X POST https://api.dropbox.com/oauth2/token \
          -d grant_type=refresh_token \
          -d refresh_token=${{ secrets.DROPBOX_REFRESH_TOKEN }} \
          -u "${{ secrets.DROPBOX_APP_KEY }}:${{ secrets.DROPBOX_APP_SECRET }}" \
          -H "Content-Type: application/x-www-form-urlencoded")
        ACCESS_TOKEN=$(echo $response | jq -r '.access_token')
        echo "::add-mask::$ACCESS_TOKEN"
        echo "DROPBOX_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        DROPBOX_TOKEN: ${{ env.DROPBOX_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all
